### ISSUE TITLE
Use of latest kernel

### ISSUE THREAD

**Issue by Soosgang** [pgj/freebsd-wifibox-port#3]
Would it be possible to have a branch with alpine on the latest kernel? I am specifically looking for mt76 AP support; https://patchwork.kernel.org/project/linux-mediatek/patch/8868a55bcaec80822e5b671c7a6023583d1b16b0.1649269260.git.objelf@gmail.com/

I tried to figure out how to modify the port but really I have no clue, maybe you could point me to some resources and I'll try it myself.

Thx

**Comment by pgj** [comment]
Hi @ffl-la, thanks for the suggestion.  I assume you are talking about some Linux version that is more recent than 5.15 which is currently in use for the Alpine-based image, such as 6.1 or 6.2.  I originally chose 5.15 because that is what vanilla Alpine ships for their stable branches (e.g. 3.17.2), although I am aware that [they have 6.1 on their `edge` branch](https://pkgs.alpinelinux.org/package/edge/main/x86_64/linux-lts).

Ideally I would say that if you wanted to switch to 6.1, all you have to do is to change the reference to the corresponding APK package and it will be included in the image:

https://github.com/pgj/freebsd-wifibox-port/blob/c4a6cadca18d7a37d94768605c3f55864e6d8b72/net/wifibox-alpine/Makefile#L119-L133

There are two major problems with this approach.  First, the `Makefile` is tuned to work with `3.17.2`.  That is relatively easy to address, the `_ALPINE_SITE` variable needs to be set properly.  Unfortunately, changing the `ALPINE_VERSION` itself will not work, because it implicitly assumes the `v` prefix, so using `edge` there is not enough:

https://github.com/pgj/freebsd-wifibox-port/blob/c4a6cadca18d7a37d94768605c3f55864e6d8b72/net/wifibox-alpine/Makefile#L92-L102

Second, the `linux-lts` package is not the vanilla one from Alpine upstream, but a heavily optimized version.  The customized port can be found in the [`freebsd-wifibox-alpine`](https://github.com/pgj/freebsd-wifibox-alpine) repository, under [`aports/linux-lts`](https://github.com/pgj/freebsd-wifibox-alpine/tree/0ba9883f821b604ec0acd5f70a70a9108502cd7f/aports/linux-lts).  The resulting package is hosted on GitHub (as part of  `freebsd-wifibox-alpine`) and that is what the `:wifibox` suffix means above in the list of packages.  This means is that I always rebuild the package with the Wifibox-specific configuration and patches on an Alpine Linux VM.

This setup also offers the way to extend the capabilities of the vanilla Linux 5.15 if something is missing there.  An example of that is [another MT76-specific patch](https://github.com/pgj/freebsd-wifibox-alpine/blob/0ba9883f821b604ec0acd5f70a70a9108502cd7f/aports/linux-lts/0001-mt76-mt7921-add-support-for-PCIe-ID-0x0608.patch), which has been included specifically.  Maybe something similar could be done in this case hence provide a fix for the problem.

I can take a chance with this suggested path and make you available a version that includes the necessary patches that you can test.

**Comment by pgj** [comment]
So you say that only the patch you cited above should be added that would be all?

**Comment by ffl-la** [comment]
For my issue I think so, yes

**Comment by pgj** [comment]
I have checked the patch but I could not easily apply to the 5.15 sources.  Which means I will have to possibly take a leap of faith and move to Linux 6.1.  This may take a bit longer as this requires rebasing the current set of kernel configuration to this new version and adjust the extra drivers.  I will get back to you once there is something to test.

**Comment by pgj** [comment]
Please note that both the update to Linux 6.1 and optional support for Linux 6.5 have been merged into `main` by #5.

**Comment by pgj** [comment]
The request has been implemented.  No feedback from the submitter for more than a month.  Closing the issue as completed.
